### ISSUE TITLE
Idea: Automatic location

### ISSUE THREAD

**Issue by turannul** [pock/weather-widget#9]
This feature definitely missing in widget.

**Comment by turannul** [comment]
This app seems not maintained

**Comment by cshariq** [comment]
I have implemented this in a pull request that i made, since this project seems to be unmaintained i compiled it myself.

If you'd like to use the updated weather widget, you can download it by clicking download on the menubar and opening it(double click), it will automatically install and replace the existing weather widget in pock:
https://1drv.ms/f/s!Avh9vuHTyquQgdEJkt0NEVijldRXzQ?e=wtfRRY

Make sure you give pock location permissions because the weather widget now dynamically updates your location using the bing maps api instead of a preset.

**Comment by turannul** [comment]
Credits to @cshariq 
You can find widget with requested feature [here](https://github.com/cshariq/weather-widget-1)
